from collections.abc import AsyncIterator
from typing import Protocol


class ObjectStorageProvider(Protocol):
    async def put(self, key: str, content: bytes) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...

    async def stream(self, key: str) -> AsyncIterator[bytes]: ...
