from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from backend.app.outcomes.domain import (
    AnalysisReadinessSnapshot,
    EffectEstimate,
    MeasurementScale,
    OutcomeDefinition,
    OutcomeDefinitionVersion,
    OutcomeMapping,
    SynthesisCandidateSet,
    TimepointWindow,
    UnitDefinition,
)


class OutcomeRepository(Protocol):
    async def create_outcome(self, **values: Any) -> OutcomeDefinition: ...
    async def get_outcome(
        self, organization_id: UUID, review_id: UUID, outcome_id: UUID
    ) -> OutcomeDefinition | None: ...
    async def list_outcomes(
        self, organization_id: UUID, review_id: UUID
    ) -> list[OutcomeDefinition]: ...
    async def create_outcome_version(self, **values: Any) -> OutcomeDefinitionVersion: ...
    async def get_outcome_version(
        self, organization_id: UUID, review_id: UUID, version_id: UUID
    ) -> OutcomeDefinitionVersion | None: ...
    async def list_outcome_versions(
        self, organization_id: UUID, review_id: UUID, outcome_id: UUID | None = None
    ) -> list[OutcomeDefinitionVersion]: ...
    async def protocol_version_exists(
        self, organization_id: UUID, review_id: UUID, protocol_version_id: UUID
    ) -> bool: ...
    async def create_timepoint_window(self, **values: Any) -> TimepointWindow: ...
    async def get_timepoint_window(
        self, organization_id: UUID, review_id: UUID, window_id: UUID
    ) -> TimepointWindow | None: ...
    async def list_timepoint_windows(
        self, organization_id: UUID, review_id: UUID
    ) -> list[TimepointWindow]: ...
    async def create_unit(self, **values: Any) -> UnitDefinition: ...
    async def get_unit(
        self, organization_id: UUID, review_id: UUID, unit_id: UUID
    ) -> UnitDefinition | None: ...
    async def list_units(self, organization_id: UUID, review_id: UUID) -> list[UnitDefinition]: ...
    async def create_scale(self, **values: Any) -> MeasurementScale: ...
    async def get_scale(
        self, organization_id: UUID, review_id: UUID, scale_id: UUID
    ) -> MeasurementScale | None: ...
    async def list_scales(
        self, organization_id: UUID, review_id: UUID
    ) -> list[MeasurementScale]: ...
    async def extraction_value_context(
        self, organization_id: UUID, review_id: UUID, extraction_value_id: UUID
    ) -> dict[str, Any] | None: ...
    async def create_mapping(self, **values: Any) -> OutcomeMapping: ...
    async def get_mapping(
        self, organization_id: UUID, review_id: UUID, mapping_id: UUID
    ) -> OutcomeMapping | None: ...
    async def list_mappings(
        self, organization_id: UUID, review_id: UUID
    ) -> list[OutcomeMapping]: ...
    async def create_effect_estimate(self, **values: Any) -> EffectEstimate: ...
    async def get_effect_estimate(
        self, organization_id: UUID, review_id: UUID, estimate_id: UUID
    ) -> EffectEstimate | None: ...
    async def list_effect_estimates(
        self, organization_id: UUID, review_id: UUID
    ) -> list[EffectEstimate]: ...
    async def evidence_article(
        self, organization_id: UUID, review_id: UUID, evidence_location_id: UUID
    ) -> UUID | None: ...
    async def create_candidate_set(self, **values: Any) -> SynthesisCandidateSet: ...
    async def get_candidate_set(
        self, organization_id: UUID, review_id: UUID, candidate_set_id: UUID
    ) -> SynthesisCandidateSet | None: ...
    async def list_candidate_sets(
        self, organization_id: UUID, review_id: UUID
    ) -> list[SynthesisCandidateSet]: ...
    async def create_readiness_snapshot(self, **values: Any) -> AnalysisReadinessSnapshot: ...
    async def list_readiness_snapshots(
        self, organization_id: UUID, review_id: UUID
    ) -> list[AnalysisReadinessSnapshot]: ...
