import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";

import {
  getAnalysisWorkspace,
  getCertaintyWorkspace,
  getOutcomeWorkspace,
} from "@/lib/api";
import { getAICertaintyProposals } from "@/lib/ai-certainty-api";

import {
  adjudicateComparison,
  compareAssessments,
  createAssessment,
  createAICertaintyPolicy,
  createSummaryOfFindings,
  installFoundation,
  requestAICertaintySuggestions,
  reviewAICertaintyProposal,
  saveDomain,
  saveFinal,
  submitAssessment,
} from "./actions";

type Props = {
  params: Promise<{ reviewId: string }>;
  searchParams: Promise<{ error?: string; updated?: string }>;
};

const field = "mt-1 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-2 text-sm";
const button = "rounded-full bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white";
const secondary = "rounded-full border border-[var(--line)] px-4 py-2 text-sm font-semibold";

export default async function CertaintyPage({ params, searchParams }: Props) {
  const [{ reviewId }, query, cookieStore] = await Promise.all([params, searchParams, cookies()]);
  const accessToken = cookieStore.get("review_access_token")?.value;
  const organizationId = cookieStore.get("review_organization_id")?.value;
  if (!accessToken || !organizationId) redirect("/login");

  const [certainty, outcomes, analysis, aiCertainty] = await Promise.all([
    getCertaintyWorkspace(accessToken, organizationId, reviewId),
    getOutcomeWorkspace(accessToken, organizationId, reviewId),
    getAnalysisWorkspace(accessToken, organizationId, reviewId),
    getAICertaintyProposals(accessToken, organizationId, reviewId),
  ]);
  if (
    certainty.status === "unauthorized" ||
    outcomes.status === "unauthorized" ||
    analysis.status === "unauthorized"
  ) {
    redirect("/login?error=session_expired");
  }
  const unavailable =
    certainty.status === "unavailable" ||
    outcomes.status === "unavailable" ||
    analysis.status === "unavailable";
  const outcomeVersions = outcomes.outcomes.flatMap((outcome) => outcome.versions);
  const outcomeById = Object.fromEntries(
    outcomeVersions.map((version) => [version.id, version.definition.name]),
  );
  const frameworkVersions = certainty.frameworks.flatMap((framework) => framework.versions);
  const frameworkById = Object.fromEntries(
    frameworkVersions.map((version) => [version.id, version]),
  );
  const currentRuns = analysis.runs.filter((run) => run.status === "COMPLETED" && !run.stale);

  return (
    <main className="mx-auto min-h-screen w-full max-w-7xl px-6 py-8 sm:px-10 lg:px-14">
      <header className="border-b border-[var(--line)] pb-7">
        <Link className="text-sm font-semibold text-[var(--brand)] hover:underline" href="/reviews">
          &larr; Review projects
        </Link>
        <p className="mt-6 text-xs font-bold uppercase tracking-[0.22em] text-[var(--brand)]">
          Human certainty judgments
        </p>
        <h1 className="mt-2 text-3xl font-semibold tracking-[-0.03em]">
          Certainty-of-evidence workspace
        </h1>
        <p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">
          Record explicit domain judgments against an outcome and evidence body. Statistical and
          Risk-of-Bias results are consumed as evidence and are never recalculated here.
        </p>
      </header>

      {query.error ? (
        <p className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">
          The certainty operation was rejected ({query.error.replaceAll("_", " ")}).
        </p>
      ) : null}
      {query.updated ? (
        <p className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">
          {query.updated.replaceAll("_", " ")}.
        </p>
      ) : null}

      {unavailable ? (
        <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">
          The certainty workspace is unavailable. No scientific record was changed.
        </section>
      ) : (
        <>
          <section className="grid gap-6 py-9 lg:grid-cols-[0.8fr_1.2fr]">
            <aside className="rounded-2xl border border-blue-200 bg-blue-50 p-6 text-sm text-blue-950">
              <h2 className="text-lg font-semibold">Foundation boundary</h2>
              <p className="mt-2">
                This is a structured, auditable foundation—not a claim of complete official GRADE
                support. No threshold, downgrade, upgrade, or final certainty is generated by AI.
              </p>
              {certainty.frameworks.length === 0 ? (
                <form action={installFoundation.bind(null, reviewId)} className="mt-5">
                  <button className={button} type="submit">
                    Install demonstration foundation
                  </button>
                </form>
              ) : (
                <p className="mt-5 font-semibold">
                  {certainty.frameworks.length} versioned framework(s) available.
                </p>
              )}
            </aside>

            <form
              action={createAssessment.bind(null, reviewId)}
              className="rounded-2xl border border-[var(--line)] bg-white p-6"
            >
              <h2 className="text-xl font-semibold">Start independent assessment</h2>
              <div className="mt-5 grid gap-4 sm:grid-cols-2">
                <label className="text-xs font-semibold">
                  Outcome version
                  <select className={field} name="outcome_version_id" required>
                    <option value="">Select outcome</option>
                    {outcomeVersions.map((version) => (
                      <option key={version.id} value={version.id}>
                        {version.definition.name} v{version.version}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="text-xs font-semibold">
                  Framework version
                  <select className={field} name="framework_version_id" required>
                    <option value="">Select framework</option>
                    {frameworkVersions.map((version) => (
                      <option key={version.id} value={version.id}>
                        {version.definition.name} v{version.version}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="text-xs font-semibold">
                  Current immutable analysis run (optional)
                  <select className={field} name="analysis_target">
                    <option value="">Narrative evidence body</option>
                    {currentRuns.map((run) => (
                      <option
                        key={run.id}
                        value={run.id + "|" + run.specification_version_id}
                      >
                        {run.result?.model ?? "Analysis"} · {run.id.slice(0, 8)}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="text-xs font-semibold">
                  Timepoint window ID
                  <input className={field} name="timepoint_window_id" />
                </label>
                <label className="text-xs font-semibold">
                  Evidence-body type
                  <select className={field} name="evidence_body_type">
                    <option>RANDOMIZED</option>
                    <option>OBSERVATIONAL</option>
                    <option>MIXED</option>
                    <option>OTHER</option>
                  </select>
                </label>
                <label className="text-xs font-semibold">
                  Explicit starting certainty
                  <select className={field} name="starting_certainty">
                    <option>HIGH</option>
                    <option>MODERATE</option>
                    <option>LOW</option>
                    <option>VERY_LOW</option>
                  </select>
                </label>
                <label className="text-xs font-semibold">
                  Round
                  <input className={field} defaultValue="1" min="1" name="round_number" type="number" />
                </label>
                <label className="text-xs font-semibold">
                  Study IDs for narrative evidence
                  <input className={field} name="study_ids" placeholder="Comma-separated IDs" />
                </label>
                <label className="text-xs font-semibold sm:col-span-2">
                  Starting-certainty rationale
                  <textarea className={field} name="starting_rationale" required />
                </label>
                <label className="text-xs font-semibold sm:col-span-2">
                  Available publication-bias evidence (optional; absence is not a downgrade)
                  <textarea className={field} name="publication_bias_note" />
                </label>
              </div>
              <button className={button + " mt-5"} type="submit">
                Create blinded assessment
              </button>
            </form>
          </section>

          <section className="border-t border-[var(--line)] py-9">
            <h2 className="text-2xl font-semibold">Assessments</h2>
            <div className="mt-6 space-y-6">
              {certainty.assessments.map((assessment) => {
                const framework = frameworkById[assessment.framework_version_id];
                return (
                  <article
                    className="rounded-2xl border border-[var(--line)] bg-white p-6"
                    key={assessment.id}
                  >
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <h3 className="font-semibold">
                          {outcomeById[assessment.outcome_version_id] ?? assessment.outcome_version_id}
                        </h3>
                        <p className="mt-1 text-xs text-[var(--muted)]">
                          Round {assessment.round_number} · revision {assessment.revision} ·{" "}
                          {assessment.status}
                        </p>
                      </div>
                      <span
                        className={
                          "rounded-full px-3 py-1 text-xs font-semibold " +
                          (assessment.stale
                            ? "bg-amber-100 text-amber-900"
                            : "bg-emerald-100 text-emerald-900")
                        }
                      >
                        {assessment.stale ? "STALE EVIDENCE" : "CURRENT EVIDENCE"}
                      </span>
                    </div>

                    {assessment.status === "IN_PROGRESS" && framework ? (
                      <div className="mt-6 grid gap-4 lg:grid-cols-2">
                        {framework.definition.domains.map((domain) => (
                          <form
                            action={saveDomain.bind(
                              null,
                              reviewId,
                              assessment.id,
                              domain.key,
                            )}
                            className="rounded-xl border border-[var(--line)] p-4"
                            key={domain.key}
                          >
                            <h4 className="font-semibold">{domain.label}</h4>
                            <p className="mt-1 text-xs text-[var(--muted)]">
                              Explicit human {domain.direction.toLowerCase()} judgment
                            </p>
                            <label className="mt-3 block text-xs font-semibold">
                              Judgment
                              <select className={field} name="judgment">
                                {domain.choices.map((choice) => (
                                  <option key={choice.value} value={choice.value}>
                                    {choice.label}
                                  </option>
                                ))}
                              </select>
                            </label>
                            <label className="mt-3 block text-xs font-semibold">
                              Rationale
                              <textarea className={field} name="rationale" required />
                            </label>
                            <label className="mt-3 block text-xs font-semibold">
                              Evidence location ID (optional)
                              <input className={field} name="evidence_location_id" />
                            </label>
                            <button className={secondary + " mt-3"} type="submit">
                              Save domain
                            </button>
                          </form>
                        ))}
                        <form
                          action={saveFinal.bind(null, reviewId, assessment.id)}
                          className="rounded-xl border border-[var(--line)] p-4 lg:col-span-2"
                        >
                          <h4 className="font-semibold">
                            Candidate: {assessment.candidate_certainty ?? "save all domains first"}
                          </h4>
                          <div className="mt-3 grid gap-3 sm:grid-cols-2">
                            <label className="text-xs font-semibold">
                              Assessor final certainty
                              <select className={field} name="final_certainty">
                                <option>HIGH</option>
                                <option>MODERATE</option>
                                <option>LOW</option>
                                <option>VERY_LOW</option>
                              </select>
                            </label>
                            <label className="text-xs font-semibold">
                              Override reason when final differs
                              <textarea className={field} name="override_reason" />
                            </label>
                            <label className="text-xs font-semibold sm:col-span-2">
                              Final rationale
                              <textarea className={field} name="final_rationale" required />
                            </label>
                          </div>
                          <button className={button + " mt-4"} type="submit">
                            Calculate candidate and save final
                          </button>
                        </form>
                        <form
                          action={submitAssessment.bind(null, reviewId, assessment.id)}
                          className="lg:col-span-2"
                        >
                          <button className={button} type="submit">
                            Submit immutable assessment
                          </button>
                        </form>
                      </div>
                    ) : (
                      <div className="mt-5">
                        <p className="text-lg font-semibold">
                          Final certainty: {assessment.final_certainty}
                        </p>
                        <p className="mt-2 text-sm text-[var(--muted)]">
                          Candidate {assessment.candidate_certainty} · evidence hash{" "}
                          {assessment.evidence_hash?.slice(0, 12)}
                        </p>
                        <form
                          action={createSummaryOfFindings.bind(null, reviewId, assessment.id)}
                          className="mt-4"
                        >
                          <button className={secondary} disabled={assessment.stale} type="submit">
                            Snapshot Summary of Findings row
                          </button>
                        </form>
                      </div>
                    )}
                  </article>
                );
              })}
            </div>
          </section>

          <section className="border-t border-[var(--line)] py-9">
            <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]">
              <div>
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--brand)]">
                  Governed assistance
                </p>
                <h2 className="mt-2 text-2xl font-semibold">Certainty drafting assistant</h2>
                <p className="mt-2 text-sm text-[var(--muted)]">
                  The assistant summarizes selected parsed evidence and proposes only framework-
                  permitted domain judgments. It cannot calculate, choose, or save final certainty.
                  A human must inspect the pinned evidence and submit any canonical payload.
                </p>
                <form
                  action={createAICertaintyPolicy.bind(null, reviewId)}
                  className="mt-5 space-y-3 rounded-xl bg-[#edf4f0] p-4"
                >
                  <label className="block text-xs font-semibold">
                    Maximum proposal batch size
                    <input
                      className={field}
                      defaultValue="20"
                      min="1"
                      max="100"
                      name="maximum_batch_size"
                      type="number"
                    />
                  </label>
                  <button className={button} type="submit">
                    Save governed policy
                  </button>
                </form>
              </div>
              <div className="space-y-4">
                {certainty.assessments
                  .filter((assessment) => assessment.status === "IN_PROGRESS")
                  .map((assessment) => (
                    <form
                      action={requestAICertaintySuggestions.bind(null, reviewId, assessment.id)}
                      className="rounded-xl border border-[var(--line)] bg-white p-5"
                      key={assessment.id}
                    >
                      <h3 className="font-semibold">Prepare evidence-grounded suggestions</h3>
                      <p className="mt-1 break-all font-mono text-xs text-[var(--muted)]">
                        Assessment {assessment.id}
                      </p>
                      <label className="mt-4 block text-xs font-semibold">
                        Processed source Document UUIDs
                        <textarea
                          className={field}
                          name="document_ids"
                          placeholder="Document UUIDs separated by commas"
                          required
                        />
                      </label>
                      <button className={button + " mt-4"} type="submit">
                        Generate bounded suggestions
                      </button>
                    </form>
                  ))}
                {certainty.assessments.every((assessment) => assessment.status !== "IN_PROGRESS") ? (
                  <p className="rounded-xl border border-[var(--line)] p-5 text-sm text-[var(--muted)]">
                    New assistance is available only while an assessment is in progress.
                  </p>
                ) : null}
                {aiCertainty.status === "unauthorized" ? (
                  <p className="text-sm text-[var(--muted)]">
                    Certainty assistance is restricted to authorized review roles.
                  </p>
                ) : null}
                {aiCertainty.status === "unavailable" ? (
                  <p className="text-sm text-amber-800">
                    Certainty assistance is temporarily unavailable; canonical records are unaffected.
                  </p>
                ) : null}
              </div>
            </div>

            {aiCertainty.status === "ready" && aiCertainty.proposals.length > 0 ? (
              <div className="mt-8 space-y-5">
                <h3 className="text-xl font-semibold">Proposals awaiting human disposition</h3>
                {aiCertainty.proposals.map((proposal) => {
                  const value = proposal.structured_value;
                  return (
                    <article
                      className="rounded-2xl border border-[var(--line)] bg-white p-5"
                      key={proposal.proposal_id ?? `${proposal.assessment_id}-${proposal.ai_run_id}`}
                    >
                      <div className="flex flex-wrap items-start justify-between gap-3">
                        <div>
                          <h4 className="font-semibold">
                            {value?.abstention ? "Assistant abstained" : "Domain suggestions"}
                          </h4>
                          <p className="mt-1 break-all font-mono text-xs text-[var(--muted)]">
                            Assessment {proposal.assessment_id} · {proposal.status}
                          </p>
                        </div>
                        <span
                          className={
                            "rounded-full px-3 py-1 text-xs font-semibold " +
                            (proposal.stale
                              ? "bg-amber-100 text-amber-900"
                              : proposal.validation_results?.aggregate_valid
                                ? "bg-[#edf4f0] text-emerald-900"
                                : "bg-amber-100 text-amber-900")
                          }
                        >
                          {proposal.stale
                            ? "STALE"
                            : proposal.validation_results?.aggregate_valid
                              ? "VALIDATED"
                              : "REVIEW REQUIRED"}
                        </span>
                      </div>
                      <p className="mt-3 text-sm text-[var(--muted)]">
                        {value?.abstention_reason ?? value?.evidence_summary ?? proposal.failure_reason ?? "No summary returned."}
                      </p>
                      {value?.domain_suggestions?.length ? (
                        <div className="mt-4 grid gap-3 lg:grid-cols-2">
                          {value.domain_suggestions.map((suggestion) => (
                            <div className="rounded-xl bg-[#f7f8f6] p-4" key={suggestion.domain_key}>
                              <p className="font-semibold">{suggestion.domain_key}</p>
                              <p className="mt-1 text-sm">
                                {suggestion.judgment} · magnitude {suggestion.magnitude}
                              </p>
                              <p className="mt-1 text-xs text-[var(--muted)]">{suggestion.rationale}</p>
                              <p className="mt-2 text-xs text-[var(--muted)]">
                                {suggestion.evidence.length} pinned evidence item(s)
                              </p>
                            </div>
                          ))}
                        </div>
                      ) : null}
                      <details className="mt-4 rounded-xl bg-[#f7f8f6] p-3">
                        <summary className="cursor-pointer text-xs font-semibold">
                          Inspect pinned proposal and validation
                        </summary>
                        <pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words text-[11px]">
                          {JSON.stringify(
                            {
                              structured_value: value,
                              validation_results: proposal.validation_results,
                              stale_reasons: proposal.stale_reasons,
                              source_manifest: proposal.source_manifest,
                              selected_chunk_ids: proposal.selected_chunk_ids,
                            },
                            null,
                            2,
                          )}
                        </pre>
                      </details>
                      {proposal.proposal_id ? (
                        <form
                          action={reviewAICertaintyProposal.bind(null, reviewId, proposal.proposal_id)}
                          className="mt-5 grid gap-3 border-t border-[var(--line)] pt-4 lg:grid-cols-4"
                        >
                          <label className="text-xs font-semibold">
                            Human disposition
                            <select className={field} name="action">
                              <option>REJECTED</option>
                              <option>UNRESOLVED</option>
                              <option>EDITED</option>
                              <option>ACCEPTED</option>
                            </select>
                          </label>
                          <label className="text-xs font-semibold">
                            Canonical action
                            <select className={field} name="canonical_action">
                              <option value="">No canonical write</option>
                              <option>SAVE_DOMAIN_JUDGMENTS</option>
                            </select>
                          </label>
                          <label className="text-xs font-semibold lg:col-span-2">
                            Human canonical payload (JSON)
                            <textarea
                              className={field + " font-mono text-[11px]"}
                              name="human_payload"
                              placeholder='{"domains":[{"domain_key":"IMPRECISION","judgment":"NO_CONCERN","rationale":"..."}]}'
                            />
                          </label>
                          <label className="text-xs font-semibold lg:col-span-3">
                            Reason
                            <input className={field} name="reason" />
                          </label>
                          <button className={button + " self-end"} type="submit">
                            Record disposition
                          </button>
                        </form>
                      ) : null}
                    </article>
                  );
                })}
              </div>
            ) : null}
          </section>

          <section className="grid gap-6 border-t border-[var(--line)] py-9 lg:grid-cols-2">
            <form
              action={compareAssessments.bind(null, reviewId)}
              className="rounded-2xl border border-[var(--line)] bg-white p-6"
            >
              <h2 className="text-xl font-semibold">Reveal and compare</h2>
              <p className="mt-2 text-sm text-[var(--muted)]">
                Candidate metadata contains no judgments. Content is revealed only when comparison
                is recorded.
              </p>
              {(["assessment_a_id", "assessment_b_id"] as const).map((name, index) => (
                <label className="mt-4 block text-xs font-semibold" key={name}>
                  Assessor {index + 1}
                  <select className={field} name={name} required>
                    <option value="">Select submitted assessment</option>
                    {certainty.comparisonCandidates.map((candidate) => (
                      <option key={candidate.id} value={candidate.id}>
                        {outcomeById[candidate.outcome_version_id] ?? candidate.outcome_version_id} ·
                        round {candidate.round_number} · assessor {candidate.assessor_user_id.slice(0, 8)}
                      </option>
                    ))}
                  </select>
                </label>
              ))}
              <button className={button + " mt-5"} type="submit">
                Reveal and detect disagreement
              </button>
            </form>

            <div className="space-y-4">
              {certainty.comparisons.map((comparison) => (
                <article
                  className="rounded-2xl border border-[var(--line)] bg-white p-6"
                  key={comparison.id}
                >
                  <h2 className="font-semibold">
                    {comparison.status} · {comparison.differences.length} difference(s)
                  </h2>
                  {comparison.status === "CONFLICT" ? (
                    <form
                      action={adjudicateComparison.bind(null, reviewId, comparison.id)}
                      className="mt-4"
                    >
                      <label className="text-xs font-semibold">
                        Resolution
                        <select className={field} name="resolution_assessment_id">
                          <option value={comparison.assessment_a_id}>Assessment A</option>
                          <option value={comparison.assessment_b_id}>Assessment B</option>
                        </select>
                      </label>
                      <label className="mt-3 block text-xs font-semibold">
                        Human adjudication rationale
                        <textarea className={field} name="rationale" required />
                      </label>
                      <button className={button + " mt-4"} type="submit">
                        Preserve conflict and adjudicate
                      </button>
                    </form>
                  ) : null}
                </article>
              ))}
            </div>
          </section>

          <section className="border-t border-[var(--line)] py-9">
            <h2 className="text-2xl font-semibold">Summary-of-Findings foundation</h2>
            <p className="mt-2 text-sm text-[var(--muted)]">
              {certainty.summaryOfFindings.length} immutable structured row snapshot(s). Absolute
              effects remain explicitly unavailable until a validated baseline-risk method exists.
            </p>
          </section>
        </>
      )}
    </main>
  );
}
