from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from backend.app.risk_of_bias.domain import (
    InstrumentDecision,
    RiskOfBiasAssessment,
    RiskOfBiasComparison,
    RiskOfBiasInstrument,
    RiskOfBiasInstrumentVersion,
)


class RiskOfBiasRepository(Protocol):
    async def create_instrument(self, **values: Any) -> RiskOfBiasInstrument: ...
    async def get_instrument(
        self, organization_id: UUID, review_id: UUID, instrument_id: UUID
    ) -> RiskOfBiasInstrument | None: ...
    async def list_instruments(
        self, organization_id: UUID, review_id: UUID
    ) -> list[RiskOfBiasInstrument]: ...
    async def create_version(self, **values: Any) -> RiskOfBiasInstrumentVersion: ...
    async def get_version(
        self, organization_id: UUID, review_id: UUID, version_id: UUID
    ) -> RiskOfBiasInstrumentVersion | None: ...
    async def list_versions(
        self, organization_id: UUID, review_id: UUID, instrument_id: UUID
    ) -> list[RiskOfBiasInstrumentVersion]: ...
    async def decide_version(
        self,
        *,
        version: RiskOfBiasInstrumentVersion,
        decision: InstrumentDecision,
        decided_by_user_id: UUID,
        reason: str | None,
    ) -> RiskOfBiasInstrumentVersion: ...
    async def create_assessment(self, **values: Any) -> RiskOfBiasAssessment: ...
    async def get_assessment(
        self, organization_id: UUID, review_id: UUID, assessment_id: UUID
    ) -> RiskOfBiasAssessment | None: ...
    async def list_assessments(
        self, organization_id: UUID, review_id: UUID, *, assessor_user_id: UUID | None = None
    ) -> list[RiskOfBiasAssessment]: ...
    async def save_answer(self, **values: Any) -> RiskOfBiasAssessment: ...
    async def save_domain_judgment(self, **values: Any) -> RiskOfBiasAssessment: ...
    async def save_overall(self, **values: Any) -> RiskOfBiasAssessment: ...
    async def submit_assessment(self, assessment: RiskOfBiasAssessment) -> RiskOfBiasAssessment: ...
    async def get_evidence_article(
        self, organization_id: UUID, review_id: UUID, evidence_location_id: UUID
    ) -> UUID | None: ...
    async def get_comparison_for_pair(
        self, organization_id: UUID, review_id: UUID, assessment_a_id: UUID, assessment_b_id: UUID
    ) -> RiskOfBiasComparison | None: ...
    async def create_comparison(self, **values: Any) -> RiskOfBiasComparison: ...
    async def get_comparison(
        self, organization_id: UUID, review_id: UUID, comparison_id: UUID
    ) -> RiskOfBiasComparison | None: ...
    async def list_comparisons(
        self, organization_id: UUID, review_id: UUID
    ) -> list[RiskOfBiasComparison]: ...
    async def adjudicate(self, **values: Any) -> RiskOfBiasComparison: ...
