from __future__ import annotations

from typing import Any, Protocol
from uuid import UUID

from backend.app.certainty.domain import (
    CertaintyAssessment,
    CertaintyComparison,
    CertaintyFramework,
    CertaintyFrameworkVersion,
    DecisionThresholdVersion,
    SummaryOfFindingsSnapshot,
)


class CertaintyRepository(Protocol):
    async def create_framework(self, **values: Any) -> CertaintyFramework: ...
    async def get_framework(
        self, organization_id: UUID, review_id: UUID, framework_id: UUID
    ) -> CertaintyFramework | None: ...
    async def list_frameworks(
        self, organization_id: UUID, review_id: UUID
    ) -> list[CertaintyFramework]: ...
    async def create_framework_version(self, **values: Any) -> CertaintyFrameworkVersion: ...
    async def get_framework_version(
        self, organization_id: UUID, review_id: UUID, version_id: UUID
    ) -> CertaintyFrameworkVersion | None: ...
    async def list_framework_versions(
        self, organization_id: UUID, review_id: UUID, framework_id: UUID | None = None
    ) -> list[CertaintyFrameworkVersion]: ...
    async def create_threshold_version(self, **values: Any) -> DecisionThresholdVersion: ...
    async def get_threshold_version(
        self, organization_id: UUID, review_id: UUID, version_id: UUID
    ) -> DecisionThresholdVersion | None: ...
    async def list_threshold_versions(
        self, organization_id: UUID, review_id: UUID
    ) -> list[DecisionThresholdVersion]: ...
    async def create_assessment(self, **values: Any) -> CertaintyAssessment: ...
    async def get_assessment(
        self, organization_id: UUID, review_id: UUID, assessment_id: UUID
    ) -> CertaintyAssessment | None: ...
    async def list_assessments(
        self, organization_id: UUID, review_id: UUID, assessor_user_id: UUID | None = None
    ) -> list[CertaintyAssessment]: ...
    async def save_domain(self, **values: Any) -> CertaintyAssessment: ...
    async def save_final(self, **values: Any) -> CertaintyAssessment: ...
    async def submit(self, **values: Any) -> CertaintyAssessment: ...
    async def create_comparison(self, **values: Any) -> CertaintyComparison: ...
    async def get_comparison(
        self, organization_id: UUID, review_id: UUID, comparison_id: UUID
    ) -> CertaintyComparison | None: ...
    async def get_comparison_for_pair(
        self, organization_id: UUID, review_id: UUID, first_id: UUID, second_id: UUID
    ) -> CertaintyComparison | None: ...
    async def list_comparisons(
        self, organization_id: UUID, review_id: UUID
    ) -> list[CertaintyComparison]: ...
    async def adjudicate(self, **values: Any) -> CertaintyComparison: ...
    async def create_sof_snapshot(self, **values: Any) -> SummaryOfFindingsSnapshot: ...
    async def list_sof_snapshots(
        self, organization_id: UUID, review_id: UUID
    ) -> list[SummaryOfFindingsSnapshot]: ...
    async def evidence_location_exists(
        self, organization_id: UUID, review_id: UUID, evidence_location_id: UUID
    ) -> bool: ...
